### ISSUE TITLE
JsonSyntaxException in Webhooks Endpoint

### ISSUE THREAD

**Issue by hkeeble1** [contentful/contentful-management.java#149]
Hello,

I'm seeing an exception thrown from inside the SDK when attempting to retrieve webhooks. It's happening when retrieving all webhooks, or a single webhook. I'm using Java 11 and SDK version 3.4.2, but from my testing it appears the issue occurs from 3.4.0 onwards.

Here is a simple Java application in which I've reproduced the issue:
```java
import com.contentful.java.cma.CMAClient;
import com.contentful.java.cma.model.CMAArray;
import com.contentful.java.cma.model.CMAWebhook;

public class Application {
	private final static String TOKEN = "PERSONAL_ACCESS_TOKEN";
	private final static String SPACE = "SPACE_ID";

	public static void main(String[] args) {
		CMAClient client = new CMAClient
				.Builder()
				.setAccessToken(TOKEN)
				.setSpaceId(SPACE)
				.build();

		CMAArray<CMAWebhook> webhooks = client.webhooks().fetchAll();

		System.out.println(webhooks.getItems().get(0).getName());
	}
}
```
This built using Maven and Java 11, I've not pulled in any other libraries, so the SDK is using `HttpURLConnection`. I get the same issue however if I add OkHttp 4.9.3 to my dependencies (the only difference being I see OkHttp being used the call stack of the exception).

The exception is thrown on this line:
```java
CMAArray<CMAWebhook> webhooks = client.webhooks().fetchAll();
```

The exception is:
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 29 column 17 path $.items[0].transformation.body
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
	at io.reactivex.Observable.subscribe(Observable.java:12246)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:12246)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.blockingFirst(Flowable.java:5607)
	at com.contentful.java.cma.ModuleWebhooks.fetchAll(ModuleWebhooks.java:208)
	at com.contentful.java.cma.ModuleWebhooks.fetchAll(ModuleWebhooks.java:189)
	at com.contentful.java.cma.ModuleWebhooks.fetchAll(ModuleWebhooks.java:158)
	at Application.main(Application.java:16)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 29 column 17 path $.items[0].transformation.body
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:401)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:389)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	... 24 more
```

Debugging through this, I can see that the part of the object it is having difficulty reading in the response JSON is:
```json
      "transformation":{
        "method":"PUT",
        "contentType":"application/json",
        "body":{
          "topic":"{ /topic }",
          "user":"{ /user }",
          "entity":"{ /payload }"
        }
```
With line 29 referenced above being the `body` property.

I'm having to revert for the time being to using an HTTP client directly instead to make this call (as I don't want to use older versions as Maven lists some vulnerabilities).

Any help greatly appreciated!

**Comment by rafalniski** [comment]
Hey @hkeeble1 fix for that will be released soon - here is the [PR](https://github.com/contentful/contentful-management.java/pull/153)

**Comment by rafalniski** [comment]
Hey @hkeeble1 this should be fixed now in v.3.4.4

**Comment by hkeeble1** [comment]
That's awesome, thanks @rafalniski!
