### ISSUE TITLE
Error while creating a reference field

### ISSUE THREAD

**Issue by rmohanreddy** [contentful/contentful-management.java#55]
Hi

When I try to create a reference field, I get below error.  Please help.

I am constructing below object using contentful-management.java api
{name={en-US=Test Data}, parentId={en-US={sys={type=Link,linkType=Entry,id=dffssdfsdfsfdsfdsdf}}}}

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: FAILED REQUEST: Request{method=POST, url=https://api.contentful.com/spaces/sdfewr/entries, tag=Request{method=POST, url=https://api.contentful.com/spaces/sdfewr/entries, tag=null}}
	… Response{protocol=http/1.1, code=422, message=Unprocessable Entity, url=https://api.contentful.com/spaces/sdfewr/entries}
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:472)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:169)
	at com.contentful.java.cma.ModuleEntries.create(ModuleEntries.java:79)

**Comment by mariobodemann** [comment]
Hello,

can you give me a helping hand in helping you? I would like to understand how you did construct your object, and how you are pushing it to our CMA. 

Can you provide some more Code?

Thanks,
Mario

**Comment by mariobodemann** [comment]
Hello @rmohanreddy,

I will close this issue due to inactivity. Please feel free to open up this issue again, if needed.

Greetings,
Mario
